---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: airflow
  region: us-west-1
  version: "1.18"

managedNodeGroups:
  - name: workers
    instanceType: t2.large
    privateNetworking: true
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: Naresh-california
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        autoScaler: true
